name: Daily Scan and Fix

on:
  schedule:
    - cron: '0 0 * * *' # 毎日0時(UTC)に実行
  workflow_dispatch: # 手動実行も可能にする

jobs:
  scan-and-fix:
    name: Scan and Fix (${{ matrix.language }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'actions' ]
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }} # プロジェクトに合わせて言語を指定

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"
          output: ../results

      - name: Run AI Agent to Fix Vulnerabilities
        uses: docker://ghcr.io/daichi213/gcp_poc_oss_llm_project:codeql-fix-agent # GHCRのイメージパスを指定
        with:
          sarif: ../results/sarif.json
          code-dir: .
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'fix: Auto-fix vulnerabilities by AI Agent for ${{ matrix.language }}'
          branch: ai-fixes/daily-scan-${{ matrix.language }}
          base: main
          title: '[AI] Automated Vulnerability Fixes for ${{ matrix.language }}'
          body: |
            This PR was automatically generated by the AI Agent to fix vulnerabilities detected by CodeQL for ${{ matrix.language }}.
            Please review the changes carefully before merging.
          labels: ai-generated