name: 'ci_terraform_plan'

on:
  issue_comment:
    types: [created]

jobs:
  plan:
    if: github.event.issue.pull_request && github.event.comment.body == '/terraform plan'
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'       # GCP Workload Identity Federationに必要
      contents: 'read'
      pull-requests: 'write'  # PRへのコメント投稿に必要

    steps:
      - name: 'Get branch name'
        id: get_branch
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            return pr.data.head.ref;

      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.get_branch.outputs.result }}

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_CI }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_CI }}

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3 # バージョンをv3に更新
        with:
          terraform_version: 1.5.4

      # Cacheステップはディレクトリ指定を修正
      - name: 'Cache Terraform providers'
        uses: actions/cache@v3
        with:
          path: ./google_cloud_infra/.terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('./google_cloud_infra/.terraform.lock.hcl') }}

      - name: 'Terraform Init'
        id: init
        run: terraform init -no-color
        working-directory: ./google_cloud_infra

      - name: 'Terraform Validate'
        id: validate
        run: terraform validate -no-color
        working-directory: ./google_cloud_infra

      - name: 'Terraform Plan'
        id: plan
        run: terraform plan -no-color -out=tfplan
        working-directory: ./google_cloud_infra

      - name: 'Terraform Show'
        id: show
        if: steps.plan.outcome == 'success'
        working-directory: ./google_cloud_infra
        run: |
          PLAN_OUTPUT=$(terraform show -no-color tfplan)

          # マルチラインの出力を安全に次のステップに渡す
          DELIMITER=$(openssl rand -hex 8)
          {
            echo "plan_output<<$DELIMITER"
            echo '```terraform'
            echo "$PLAN_OUTPUT"
            echo '```'
            echo "$DELIMITER"
          } >> "$GITHUB_OUTPUT"

      - name: 'Comment on PR'
        uses: actions/github-script@v7
        if: always() # 常に実行して結果をレポート
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { init, validate, plan, show } = ${{ toJson(steps) }};
            let body;

            if (init.outcome !== 'success') {
              body = `#### Terraform Init Failed ❌

              Please check the workflow logs for more details.`;
            } else if (validate.outcome !== 'success') {
              body = `#### Terraform Validate Failed ❌

              Please check the workflow logs for more details.`;
            } else if (plan.outcome !== 'success') {
              body = `#### Terraform Plan Failed ❌

              An error occurred during the plan. Please check the workflow logs.`;
            } else {
              const output = `${{ steps.show.outputs.plan_output }}`;
              
              body = `#### Terraform Plan Succeeded ✅

              Changes are proposed in the plan below:

              ${output}`;
            }

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });